uploads = []

[[generated]]
id = "nbX4JVlf_6yZUZtAwrV9D"
uri = "file://artifacts/pulse/public/gifts/rose-in-glass.png"
type = "image"
title = "rose in glass dome"

[[generated]]
id = "XsYTfwUTDnsULmKl7mIG6"
uri = "file://artifacts/pulse/public/gifts/gaming-console.png"
type = "image"
title = "gaming console with bow"

[[generated]]
id = "yeJhbEjzb9B0UWss9RPSO"
uri = "file://artifacts/pulse/public/gifts/star-42.png"
type = "image"
title = "shining star 42"

[[generated]]
id = "23Ob4PC7Vt_FzGQAKit_O"
uri = "file://artifacts/pulse/public/gifts/teddy-bear.png"
type = "image"
title = "teddy bear with heart"

[[generated]]
id = "VvMWGVTfULOLv9JyIWRHc"
uri = "file://artifacts/pulse/public/gifts/birthday-cake.png"
type = "image"
title = "birthday cake with candles"

[[generated]]
id = "ayWfvHrJ94XoepWru1eqb"
uri = "file://artifacts/pulse/public/gifts/confetti-box.png"
type = "image"
title = "confetti gift box"

[[generated]]
id = "ET4rsjRbYnXu0XET_Oi_n"
uri = "file://artifacts/pulse/public/gifts/gold-coin.png"
type = "image"
title = "golden coin sparkle"

[[generated]]
id = "iRNERvIiZ9jsUkxWd991d"
uri = "file://artifacts/pulse/public/gifts/magic-crystal.png"
type = "image"
title = "magic crystal ball"

[[generated]]
id = "tkAblFjTj4cB8C6clKiWR"
uri = "file://artifacts/pulse/public/gifts/retro-phone.png"
type = "image"
title = "retro rotary phone"

[[generated]]
id = "37_eLrScYidDewcq_4S3g"
uri = "file://artifacts/pulse/public/gifts/diamond-heart.png"
type = "image"
title = "diamond heart gem"

[[generated]]
id = "yATPiAVQQZwXDW7bonUFE"
uri = "file://artifacts/pulse/public/gifts/heart.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ecCvKVEZxVJ5fYyU1qTL5"
uri = "file://artifacts/pulse/public/gifts/star-small.png"
type = "image"
title = "generated_image"

[[generated]]
id = "NPqep5rlhzK6cA7D3ym9e"
uri = "file://artifacts/pulse/public/gifts/sakura.png"
type = "image"
title = "generated_image"

[[generated]]
id = "svUSK1PCk3yQ4ojl0Qtjv"
uri = "file://artifacts/pulse/public/gifts/donut.png"
type = "image"
title = "generated_image"

[[generated]]
id = "rSPGWDoaMG95Kso6__LgY"
uri = "file://artifacts/pulse/public/gifts/kitten.png"
type = "image"
title = "generated_image"

[[generated]]
id = "uF4--oHA_cgdDdRahpxpD"
uri = "file://artifacts/pulse/public/gifts/balloon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "YilNsbnkm-zipoQWO6e6R"
uri = "file://artifacts/pulse/public/gifts/clover.png"
type = "image"
title = "generated_image"

[[generated]]
id = "hiBG3IIctnhColDF2TqEl"
uri = "file://artifacts/pulse/public/gifts/pizza.png"
type = "image"
title = "generated_image"

[[generated]]
id = "QwFMJOpOaZmrOMGPxSDiY"
uri = "file://artifacts/pulse/public/gifts/moon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "s_G6cFV0hNWq8UgJglQzn"
uri = "file://artifacts/pulse/public/gifts/crown.png"
type = "image"
title = "generated_image"

[[generated]]
id = "G7C99BR08_DaV00CGQuu4"
uri = "file://artifacts/pulse/public/gifts/daisy.png"
type = "image"
title = "generated_image"

[[generated]]
id = "PFqwOYZ4mzgcl9xtZgmUI"
uri = "file://artifacts/pulse/public/gifts/icecream.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Mah-FFrglkvz0Z4beKE8T"
uri = "file://artifacts/pulse/public/gifts/lollipop.png"
type = "image"
title = "generated_image"

[[generated]]
id = "xJgcj1A8lxEyZBt5m5pdq"
uri = "file://artifacts/pulse/public/gifts/butterfly.png"
type = "image"
title = "generated_image"

[[generated]]
id = "8K9kn0WgVdDpAZYx55Y6B"
uri = "file://artifacts/pulse/public/gifts/sunflower.png"
type = "image"
title = "generated_image"

[[generated]]
id = "5nECWaEpTs_9A9VxSGerN"
uri = "file://artifacts/pulse/public/gifts/strawberry.png"
type = "image"
title = "generated_image"

[[generated]]
id = "QqJVIYYYW6Ys5_jdC7Ry2"
uri = "file://artifacts/pulse/public/gifts/coffee.png"
type = "image"
title = "generated_image"

[[generated]]
id = "VojeCwq3_C9I7OzhooGUr"
uri = "file://artifacts/pulse/public/gifts/fish.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ctOThKB04fu9AWP7WhAYJ"
uri = "file://artifacts/pulse/public/gifts/candy.png"
type = "image"
title = "generated_image"

[[generated]]
id = "S1vvHWFnWSJXULaseniBg"
uri = "file://artifacts/pulse/public/gifts/bubble.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "lhkcHx0fkaD2JKBZ0j9yt"
uri = "file://artifacts/pulse/public/gifts/rose-in-glass.png"
type = "image"
title = "Роза в стеклянной колбе"

[[outputs]]
id = "CXJT07v78f8P9BY7XgCfA"
uri = "file://artifacts/pulse/public/gifts/gaming-console.png"
type = "image"
title = "Игровая приставка с бантом"

[[outputs]]
id = "fzX5und7WlHFOxyHFjsmM"
uri = "file://artifacts/pulse/public/gifts/star-42.png"
type = "image"
title = "Сияющая звезда #42"

[[outputs]]
id = "Ox-RgYZDnNBrX9jdYDQ6-"
uri = "file://artifacts/pulse/public/gifts/teddy-bear.png"
type = "image"
title = "Плюшевый мишка с сердечком"

[[outputs]]
id = "iCFVyeOdC3XwpTBAfrLOv"
uri = "file://artifacts/pulse/public/gifts/birthday-cake.png"
type = "image"
title = "Торт со свечами"

[[outputs]]
id = "g1TiP6Hua33UrjRZL9HTz"
uri = "file://artifacts/pulse/public/gifts/confetti-box.png"
type = "image"
title = "Коробка с конфетти"

[[outputs]]
id = "avSKQ7rfivSEeOt8Iv7Kx"
uri = "file://artifacts/pulse/public/gifts/gold-coin.png"
type = "image"
title = "Золотая монета"

[[outputs]]
id = "9YPKHFD4S2N3VMN9_TKtG"
uri = "file://artifacts/pulse/public/gifts/magic-crystal.png"
type = "image"
title = "Магический кристалл"

[[outputs]]
id = "uweczz_YPHBLQI3rLqEXc"
uri = "file://artifacts/pulse/public/gifts/retro-phone.png"
type = "image"
title = "Ретро-телефон"

[[outputs]]
id = "6oa7aQbxJiOR2wVKaxNfY"
uri = "file://artifacts/pulse/public/gifts/diamond-heart.png"
type = "image"
title = "Алмазное сердце"
