// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/wallet-redesign/Cards.tsx": () => import("../components/mockups/wallet-redesign/Cards.tsx"),
  "./components/mockups/wallet-redesign/Glass.tsx": () => import("../components/mockups/wallet-redesign/Glass.tsx"),
  "./components/mockups/wallet-redesign/Minimal.tsx": () => import("../components/mockups/wallet-redesign/Minimal.tsx")
};
